using System.ComponentModel.DataAnnotations;
using Velocity.Shared.Enums;

namespace Velocity.Shared.Requests.PurchaseOrders;

public class CreatePurchaseOrderRequest
{
    /// <summary>
    /// Generated by the system
    /// </summary>
    public string OrderNumber { get; set; }
    
    /// <summary>
    /// Provided by the supplier from the quotation
    /// </summary>
    public string SupplierReferenceNumber { get; set; }
    
    [Required(ErrorMessage = "Order date is required")]
    public DateTime? OrderDate { get; set; }

    public IList<PurchaseOrderItemRequest> Items { get; set; } = new List<PurchaseOrderItemRequest>();
    
    public decimal SubTotal => Items.Sum(x => x.TotalPrice);
    
    public decimal TotalDiscountAmount => Items.Sum(x => x.DiscountAmount);
    
    public decimal NetTotal => Items.Sum(x => x.NetPrice);
    
    public decimal TotalTaxAmount => Items.Sum(x => x.TaxAmount);
    
    public decimal Total => Items.Sum(x => x.Total);
    
    public PurchaseOrderStatus Status { get; set; } = PurchaseOrderStatus.Placed;

    public Guid SupplierId { get; set; }
}