using System.ComponentModel.DataAnnotations;

namespace Velocity.Shared.Requests.PurchaseOrders;

public class UpdatePurchaseOrderRequest
{
    public Guid Id { get; set; }
    /// <summary>
    /// Generated by the system
    /// </summary>
    public string OrderNumber { get; set; }
    
    /// <summary>
    /// Provided by the supplier from the quotation
    /// </summary>
    public string SupplierReferenceNumber { get; set; }
    
    [Required(ErrorMessage = "Order date is required")]
    public DateTime? OrderDate { get; set; }

    public IList<PurchaseOrderItemRequest> Items { get; set; }
    
    public decimal SubTotal => Items.Sum(x => x.TotalPrice);
    
    public decimal TotalDiscountAmount => Items.Sum(x => x.DiscountAmount);
    
    public decimal NetTotal => Items.Sum(x => x.NetPrice);
    
    public decimal TotalTaxAmount => Items.Sum(x => x.TaxAmount);
    
    public decimal Total => Items.Sum(x => x.Total);

    public Guid SupplierId { get; set; }
}