namespace Velocity.Shared.Requests.PurchaseInvoices;

public class CreatePurchaseInvoiceRequest
{
    /// <summary>
    /// Generated by the system
    /// </summary>
    public string PurchaseNumber { get; set; }
    public DateTime? PurchaseDate { get; set; }
    
    /// <summary>
    /// Provided by the supplier from the supplier invoice
    /// </summary>
    public string InvoiceNumber { get; set; }
    public DateTime? InvoiceDate { get; set; }
    
    public string ReferenceNumber { get; set; }
    
    public Guid SupplierId { get; set; }
    public string Supplier { get; set; }
    
    public ICollection<PurchaseInvoiceItemRequest> Items { get; set; }
}