using Velocity.Shared.Enums;

namespace Velocity.Shared.Responses.PurchaseInvoices;

public class PurchaseInvoiceResponse
{
    public Guid Id { get; set; }
    
    /// <summary>
    /// Generated by the system
    /// </summary>
    public string PurchaseNumber { get; set; }
    public DateTime PurchaseDate { get; set; }
    
    /// <summary>
    /// Provided by the supplier from the supplier invoice
    /// </summary>
    public string InvoiceNumber { get; set; }
    public DateTime InvoiceDate { get; set; }
    
    public string ReferenceNumber { get; set; }
    
    public Guid SupplierId { get; set; }
    public string Supplier { get; set; }
    
    public PurchaseInvoiceStatus Status { get; set; } = PurchaseInvoiceStatus.Pending;
    
    public ICollection<PurchaseInvoiceItemResponse> Items { get; set; }
}

public class PurchaseInvoiceItemResponse
{
    public Guid Id { get; set; }
    
    public Guid ProductId { get; set; }
    public string Product { get; set; }
    
    public int Quantity { get; set; }
    
    public decimal UnitPrice { get; set; }
    
    /// <summary>
    /// Quantity * UnitPrice
    /// </summary>
    public decimal TotalPrice => Quantity * UnitPrice;
    
    public decimal DiscountAmount { get; set; }
    
    /// <summary>
    /// TotalPrice - Discount
    /// </summary>
    public decimal NetPrice => TotalPrice - DiscountAmount;
    
    /// <summary>
    /// TaxAmount = NetPrice * TaxPercentage / 100
    /// </summary>
    public decimal TaxAmount => NetPrice * TaxPercentage / 100;
    
    public decimal TaxPercentage { get; set; }
    
    /// <summary>
    /// NetPrice + TaxAmount
    /// </summary>
    public decimal Total => NetPrice + TaxAmount;
    
    public decimal UnitSellingPrice { get; set; }
    
    public decimal ProfitPercentage => (UnitSellingPrice - UnitPrice) / UnitPrice * 100;
    
    public decimal ProfitAmount => UnitSellingPrice - UnitPrice;
}